// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6lLMQdihHjZRk_EFybSmQTu-y_ptsVT8',
    appId: '1:27047660075:web:02cdc154b9d6ab00b5f86e',
    messagingSenderId: '27047660075',
    projectId: 'anshif-4ae5e',
    authDomain: 'anshif-4ae5e.firebaseapp.com',
    storageBucket: 'anshif-4ae5e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqzzu5fl3Lf6O704SFC8aFbvN7VKxY_lY',
    appId: '1:27047660075:android:02f6ff86288b4260b5f86e',
    messagingSenderId: '27047660075',
    projectId: 'anshif-4ae5e',
    storageBucket: 'anshif-4ae5e.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtGdXCfoyYq3bzGX95fYSUOtrSzNGUqcc',
    appId: '1:27047660075:ios:0eb4fc4eae5dde8ab5f86e',
    messagingSenderId: '27047660075',
    projectId: 'anshif-4ae5e',
    storageBucket: 'anshif-4ae5e.firebasestorage.app',
    iosBundleId: 'com.example.anshifPortolio',
  );
}
